### ISSUE TITLE
Don't see the tasks after installing the extension

### ISSUE THREAD

**Issue by mwhisler** [chrisism/VSTS.SiteOffline#1]
Lol, maybe I'm blind, but I can't seem to find these tasks after I install the extension.

**Comment by victorperez2911** [comment]
@mwhisler 


A single extension can add "N" Tasks to your Server, and these Tasks do not always have the same name as the Extension.

In the case of this extension, the task that is added to your server has the same name as the extension, just changing the icon.



![image](https://user-images.githubusercontent.com/11770654/65985777-da2abe00-e458-11e9-9eef-0663a7e993be.png)

Any more questions?
